//以下是网站顶部
document.write('<table width="760" border="0" align="center" cellspacing="0" cellpadding="0">')
document.write('<tr>')
document.write('<td width="178"><img src="../images/toplogo.gif" width="178" height="97"></td>')
document.write('<td align="center" valign="bottom" class="top"><a href="http://www.tooming.com/idc" target="_blank"><img src="http://www.pcbookcn.com/images/ads_domain.gif" border="0" width="468" height="60"></a></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td height="4" bgcolor="#FFFFFF" colspan="2"></td>')
document.write('</tr>')
document.write('</table>')
//document.write('<table cellspacing=0 cellpadding=0 width=760 align=center border=0>')
//document.write('<tr> ')
//document.write('<td width="178"><img src="../images/toplogo.gif" ></td>')
//document.write('<td width="582" class="top">')
//document.write('<div align="center"><a href="http://www.tooming.com/idc" target="_blank"><img //src="http://www.pcbookcn.com/images/ads_domain.gif" border="0" width="468" height="60"></a></div>')
//document.write('</td>')
//document.write('</tr>')
//document.write('</table>')
//以下是导航栏目
document.write('<table cellspacing=0 cellpadding=0 width=760 border=0 bgcolor="#FFFFFF" align="center">')
document.write('<tr> ')
document.write('<td width=4> ')
document.write('</td>')
document.write('<td width=95 height=31 background="../images/menu_start1.gif"> ')
document.write('<div align=left  class="font_white_bold" align=center>&nbsp;电脑书籍</div>')
document.write('</td>')
document.write('<td height=31 background="../images/menu_bg1.gif" class="font_white"><a href="http://www.pcbookcn.com/sort/1_1.htm" target="_blank" class="white_link">网站建设</a>| <a href="http://www.pcbookcn.com/sort/2_1.htm" target="_blank" class="white_link">数据库类</a>| <a href="http://www.pcbookcn.com/sort/3_1.htm" target="_blank" class="white_link">图形图象</a>| <a href="http://www.pcbookcn.com/sort/4_1.htm" target="_blank" class="white_link">程序设计</a>| <a href="http://www.pcbookcn.com/sort/5_1.htm" target="_blank" class="white_link">现代办公</a>| <a href="http://www.pcbookcn.com/sort/6_1.htm" target="_blank" class="white_link">操作系统</a>| <a href="http://www.pcbookcn.com/sort/7_1.htm" target="_blank" class="white_link">考试认证</a>| <a href="http://www.pcbookcn.com/sort/8_1.htm" target="_blank" class="white_link">网络技术</a>| <a href="http://www.pcbookcn.com/sort/9_1.htm" target="_blank" class="white_link">软件工程</a>| <a href="http://www.pcbookcn.com/sort/10_1.htm" target="_blank" class="white_link">电脑相关</a>| <a href="http://www.pcbookcn.com/sort/11_1.htm" target="_blank" class="white_link">文学作品</a></td>')
document.write('<td width=4> ')
document.write('</td>')
document.write('</tr>')
document.write('<tr> ')
document.write('<td width=4> ')
document.write('</td>')
document.write('<td height=31 width=95 background="../images/menu_start2.gif"> ')
document.write('<div align=left  class="font_white_bold" align="center">&nbsp;电脑文摘</div>')
document.write('</td>')
document.write('<td height=31 background="../images/menu_bg2.gif" class="font_white"><a href="http://www.pcbookcn.com/article/1_1.htm" target="_blank" class="white_link">网站开发</a>| <a href="http://www.pcbookcn.com/article/2_1.htm" target="_blank" class="white_link">网页制作</a>| <a href="http://www.pcbookcn.com/article/3_1.htm" target="_blank" class="white_link">操作系统</a>| <a href="http://www.pcbookcn.com/article/4_1.htm" target="_blank" class="white_link">图象图形</a>| <a href="http://www.pcbookcn.com/article/5_1.htm" target="_blank" class="white_link">考试认证</a>| <a href="http://www.pcbookcn.com/article/6_1.htm" target="_blank" class="white_link">数据库类</a>| <a href="http://www.pcbookcn.com/article/7_1.htm" target="_blank" class="white_link">程序设计</a>| <a href="http://www.pcbookcn.com/article/8_1.htm" target="_blank" class="white_link">硬件技术</a>| <a href="http://www.pcbookcn.com/article/9_1.htm" target="_blank" class="white_link">现代办公</a>| <a href="http://www.pcbookcn.com/article/11_1.htm" target="_blank" class="white_link">网络技术</a>| <a href="http://www.pcbookcn.com/article/12_1.htm" target="_blank" class="white_link">笑话频道</a></td>')
document.write('<td width=4> ')
document.write('</td>')
document.write('</tr>')
document.write('</table>')
//浅兰色的
//document.write('<table height=0 cellspacing=0 cellpadding=0 width=760 align=center border=0>')
//document.write('<tr bgcolor=#ffffff> ')
//document.write('<td></td>')
//document.write('</tr>')
//document.write('</table>')
//document.write('<table height=0 cellspacing=0 cellpadding=0 width=760 align=center border=0>')
//document.write('<tr bgcolor=#ffffff> ')
////document.write('<td align="center"><a href="http://www.tooming.com/idc" target="_blank"><img src="http://www.pcbookcn.com/images/758x90.jpg" border="0" width="752" height="90"></a> </td>')
//document.write('</tr>')
//广告位图片宽度控制在752,因为左右各留四个象素空白(蝈蝈)
//document.write('</table>')