(function(){
var i=true,l=null,m=false,aa=(new Date).getTime(),ba=function(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c};var n=this,ca=function(a,b,c){var d=a.split("."),e=c||n;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)if(!d.length&&b!==undefined)e[f]=b;else e=e[f]?e[f]:(e[f]={})},o=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},p=function(a){return o(a)=="array"},da=function(a){var b=o(a);return b=="array"||b=="object"&&typeof a.length=="number"},ea=function(a){return typeof a=="string"},fa=function(a){var b=o(a);return b=="object"||
b=="array"||b=="function"};Math.floor(Math.random()*2147483648).toString(36);
var ga=function(a){var b=o(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=ga(a[d]);return c}return a},ia=function(a,b){var c=a.u;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.w||b;a=a.v||a;var e,f=b||n;e=c?function(){var h=Array.prototype.slice.call(arguments);h.unshift.apply(h,c);return a.apply(f,h)}:function(){return a.apply(f,arguments)};e.u=c;e.w=b;e.v=a;return e},ja=Date.now||function(){return(new Date).getTime()},
q=function(a,b,c){ca(a,b,c)};function r(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function ka(a,b){if(a=="true")return i;if(a=="false")return m;return b}function s(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var la="pagead2.googlesyndication.com",ma="googleads.g.doubleclick.net",na="pubads.g.doubleclick.net",oa="securepubads.g.doubleclick.net",pa="partner.googleadservices.com",t=s("pagead2.googlesyndication.com",la),ra=s("googleads.g.doubleclick.net",ma),sa=s("pagead2.googlesyndication.com",la);s("pubads.g.doubleclick.net",na);s("partner.googleadservices.com",pa);s("securepubads.g.doubleclick.net",oa);function u(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function ta(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return m;window.setTimeout(function(){e.appendChild(d)},0);return i}function ua(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function va(a){if(a in wa)return wa[a];return wa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var wa={};
function xa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=l}return b.toString()}else if(va("msie")&&!window.opera){c=l;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(h){}}if(c){b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"}function ya(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function v(a){return!!a&&a.indexOf("_sdo")!=-1}
function w(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};var za={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Aa={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Da=
{google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};function Ea(a,b){try{return a.top.document.URL==b.URL}catch(c){}return m}function Fa(a,b,c,d){var e=c||a.google_ad_width,f=d||a.google_ad_height;if(Ea(a,b))return m;var h=b.documentElement;if(e&&f){var j=1,k=1;if(a.innerHeight){j=a.innerWidth;k=a.innerHeight}else if(h&&h.clientHeight){j=h.clientWidth;k=h.clientHeight}else if(b.body){j=b.body.clientWidth;k=b.body.clientHeight}if(k>2*f||j>2*e)return m}return i}function Ga(a,b){for(var c in b)a["google_"+c]=b[c]}
function Ha(a,b){if(!b)return a.URL;return a.referrer}function Ia(a,b){if(!b&&a.google_referrer_url==l)return"0";else if(b&&a.google_referrer_url==l)return"1";else if(!b&&a.google_referrer_url!=l)return"2";else if(b&&a.google_referrer_url!=l)return"3";return"4"}function Ja(a,b,c,d){a.page_url=Ha(c,d);a.page_location=l}function Ka(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Ha(c,d)||"EMPTY"}
function La(a,b){var c={},d=Fa(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Ia(a,d);a.google_page_url?Ka(c,a,b,d):Ja(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:l;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Ma(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=l;b.page_url=c;b.page_location=a.URL;b.last_modified_time=l;b.referrer_url=c;return b}
function Na(a,b){var c=Oa(a,b);Ga(a,c)}function Oa(a,b){var c;return c=a.google_page_url==l&&Pa[b.domain]?Ma(b):La(a,b)}var Pa={};Pa["ad.yieldmanager.com"]=i;var Qa=document,Ra=ka("false",m),Sa=ka("false",m),Ta=ka("false",m);ka("false",m);var y=window;var Ua=function(a,b,c){var d=ia(b,n,a),e=window.onerror;window.onerror=d;try{c()}catch(f){var h=f.toString(),j="";if(f.fileName)j=f.fileName;var k=-1;if(f.lineNumber)k=f.lineNumber;var g=d(h,j,k);if(!g)throw f;}window.onerror=e};q("google_protectAndRun",Ua);
var Wa=function(a,b,c,d){if(Math.random()<0.01){var e=Qa,f=["http://",t,"/pagead/gen_204","?id=jserror","&cb=",Ra?1:0,"&cd=",Sa?1:0,"&context=",u(a),"&msg=",u(b),"&file=",u(c),"&line=",u(d.toString()),"&url=",u(e.URL.substring(0,512)),"&ref=",u(e.referrer.substring(0,512))];f.push(Va());ua(y,f.join(""))}return!Ta};q("google_handleError",Wa);
var Ya=function(a){Xa|=a},Xa=0,Va=function(){var a=["&client=",u(y.google_ad_client),"&format=",u(y.google_ad_format),"&slotname=",u(y.google_ad_slot),"&output=",u(y.google_ad_output),"&ad_type=",u(y.google_ad_type)];return a.join("")};var A="",ab=function(){if(window.google_ad_frameborder==l)window.google_ad_frameborder=0;if(window.google_ad_output==l)window.google_ad_output="html";if(v(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=Za(window.google_ad_format,window.google_ad_output,window.google_ad_width,window.google_ad_height,window.google_ad_slot,
!!window.google_override_format);A=window.google_ad_client||"";window.google_ad_client=$a(window.google_ad_format,window.google_ad_client);Na(window,document);if(window.google_num_slots_by_channel==l)window.google_num_slots_by_channel={};if(window.google_viewed_host_channels==l)window.google_viewed_host_channels={};if(window.google_num_slots_by_client==l)window.google_num_slots_by_client={};if(window.google_prev_ad_formats_by_region==l)window.google_prev_ad_formats_by_region={};if(window.google_prev_ad_slotnames_by_region==
l)window.google_prev_ad_slotnames_by_region={};if(window.google_correlator==l)window.google_correlator=(new Date).getTime();if(window.google_adslot_loaded==l)window.google_adslot_loaded={};if(window.google_adContentsBySlot==l)window.google_adContentsBySlot={};if(window.google_flash_version==l)window.google_flash_version=xa();if(window.google_new_domain_checked==l)window.google_new_domain_checked=0;if(window.google_new_domain_enabled==l)window.google_new_domain_enabled=0;if(!window.google_num_ad_slots)window.google_num_ad_slots=
0;if(!window.google_num_0ad_slots)window.google_num_0ad_slots=0;if(!window.google_num_sdo_slots)window.google_num_sdo_slots=0;window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";var b=(new Date).getTime();if(p(window.google_color_bg))window.google_color_bg=C(window.google_color_bg,b);if(p(window.google_color_text))window.google_color_text=C(window.google_color_text,b);if(p(window.google_color_link))window.google_color_link=
C(window.google_color_link,b);if(p(window.google_color_url))window.google_color_url=C(window.google_color_url,b);if(p(window.google_color_border))window.google_color_border=C(window.google_color_border,b);if(p(window.google_color_line))window.google_color_line=C(window.google_color_line,b)},bb=function(a){var b;for(b in za)a[b]=l;for(b in Aa)a[b]=l;for(b in Da)a[b]=l;a.google_container_id=l;a.google_eids=l;a.google_ad_region=l;a.google_gl=l},C=function(a,b){Ya(2);return a[b%a.length]},$a=function(a,
b){if(!b)return"";b=b.toLowerCase();return b=v(a)?cb(b):db(b)},db=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},cb=function(a){if(a&&a.substring(0,9)!="dist-aff-")a="dist-aff-"+a;return a},Za=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=eb(a,e,f)?a.toLowerCase():""},eb=function(a,b,c){if(!a)return m;if(!b)return i;return c};var D=document,F=navigator,G=window;
function fb(){var a=D.cookie,b=Math.round((new Date).getTime()/1000),c=G.google_analytics_domain_name,d=typeof c=="undefined"?gb("auto"):gb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,h=a.indexOf("__utmc="+d)>-1,j,k={},g=!!G&&!!G.gaGlobal;if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&h?j[3]+"":g&&G.gaGlobal.sid?G.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=i}else{k.sid=g&&G.gaGlobal.sid?G.gaGlobal.sid:b+"";k.vid=g&&G.gaGlobal.vid?G.gaGlobal.vid:(Math.round(Math.random()*
2147483647)^hb()&2147483647)+"."+b;k.from_cookie=m}k.dh=d;k.hid=g&&G.gaGlobal.hid?G.gaGlobal.hid:Math.round(Math.random()*2147483647);return G.gaGlobal=k}
function hb(){var a=D.cookie?D.cookie:"",b=G.history.length,c,d,e=[F.appName,F.version,F.language?F.language:F.browserLanguage,F.platform,F.userAgent,F.javaEnabled()?1:0].join("");if(G.screen)e+=G.screen.width+"x"+G.screen.height+G.screen.colorDepth;else if(G.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=D.referrer?D.referrer:"";for(c=e.length;b>0;)e+=b--^c++;return ib(e)}
function ib(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function gb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=D.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return ib(a.toLowerCase())};var jb={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function kb(a){var b=a.google_page_location||a.google_page_url;if(!b)return m;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=m;if(e.length>=3)f=e[e.length-3]in jb;if(e.length>=2)f=f||e[e.length-2]in jb;return f}
function lb(a,b,c){if(kb(a)){a.google_new_domain_checked=1;return m}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://"+ra+"/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return i}}return m}function mb(a){if(!kb(a)&&a.google_new_domain_enabled==1)return"http://"+ra;return"http://"+sa};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);var nb=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},tb=function(a,b){if(b)return a.replace(ob,"&amp;").replace(pb,"&lt;").replace(qb,"&gt;").replace(rb,"&quot;");else{if(!sb.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ob,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(pb,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(qb,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(rb,"&quot;");return a}},ob=/&/g,pb=/</g,qb=/>/g,rb=/\"/g,sb=/[&<>\"]/,zb=function(a){if(H(a,"&"))return"document"in n&&!H(a,"<")?
ub(a):vb(a);return a},ub=function(a){var b=n.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},vb=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},Ab=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);
if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},H=function(a,b){return a.indexOf(b)!=-1},Cb=function(a,b){for(var c=0,d=nb(String(a)).split("."),e=nb(String(b)).split("."),f=Math.max(d.length,e.length),h=0;c==0&&h<f;h++){var j=d[h]||"",k=e[h]||"",g=new RegExp("(\\d*)(\\D*)","g"),z=new RegExp("(\\d*)(\\D*)","g");do{var E=g.exec(j)||["","",""],B=z.exec(k)||["","",""];if(E[0].length==0&&B[0].length==0)break;var X=E[1].length==0?0:parseInt(E[1],10),qa=B[1].length==
0?0:parseInt(B[1],10);c=Bb(X,qa)||Bb(E[2].length==0,B[2].length==0)||Bb(E[2],B[2])}while(c==0)}return c},Bb=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};ja();var I=function(a){this.t=a;this.i=[];this.p=this.h=0;this.d=[];this.n=m};I.prototype.s=function(a,b){var c=this.t[b],d=this.i;this.t[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:l;d.push([a,zb(e[0].url),f])}c(e)}};I.prototype.r=function(){this.h++};I.prototype.o=function(){if(!this.n){ta("http://"+t+"/pagead/osd.js");this.n=i}};I.prototype.j=function(a){if(this.h>0)for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)b.item(c).name=="google_ads_frame"&&a(b.item(c),b.item(c).src)};
I.prototype.k=function(a){var b=this.i;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=function(g,z){return g.innerHTML.indexOf(z)>0},e=0;e<c.length;e++)for(var f=0;f<b.length;f++)if(c.item(e).href==b[f][1]){var h=c.item(e).parentNode;if(b[f][2])for(var j=h,k=0;k<4;k++){if(d(j,b[f][2])){h=j;break}j=j.parentNode}a(h,b[f][0]);b.splice(f,1);break}};I.prototype.e=function(a){this.k(a);this.j(a)};I.prototype.a=function(a){this.p=a};I.prototype.g=function(){return this.p};
I.prototype.f=function(){return this.i.length+this.h};I.prototype.b=function(a){this.d=a};I.prototype.q=function(a,b){if(this.d.length>0){for(var c=0;c<this.d.length;c++)if(this.d[c]==a)if(a=="js")this.s(b,"google_ad_request_done");else a=="html"&&this.r();this.o()}};var Db=function(){window.__google_ad_urls||(window.__google_ad_urls=new I(window));return window.__google_ad_urls};q("Goog_AdSense_getAdAdapterInstance",Db);q("Goog_AdSense_OsdAdapter",I);
q("Goog_AdSense_OsdAdapter.prototype.numBlocks",I.prototype.f);q("Goog_AdSense_OsdAdapter.prototype.findBlocks",I.prototype.e);q("Goog_AdSense_OsdAdapter.prototype.getOsdMode",I.prototype.g);var Eb=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=ea(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Fb=function(a){if(p(a))return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var J=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};J.prototype.clone=function(){return new J(this.x,this.y)};J.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var K=function(a,b){this.width=a;this.height=b};K.prototype.clone=function(){return new K(this.width,this.height)};K.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};K.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};K.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
K.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};K.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Gb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var L,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb=function(){return n.navigator?n.navigator.userAgent:l},Rb=function(){return n.navigator},Sb=function(){Lb=Kb=Jb=Ib=Hb=L=m;var a;if(a=Qb()){var b=Rb();L=a.indexOf("Opera")==0;Hb=!L&&a.indexOf("MSIE")!=-1;Jb=(Ib=!L&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Lb=(Kb=!L&&!Ib&&b.product=="Gecko")&&b.vendor=="Camino"}};Sb();
var M=L,N=Hb,Tb=Kb,O=Ib,Ub=Jb,Vb=function(){var a=Rb();return a&&a.platform||""},Wb=Vb(),Xb=function(){Mb=H(Wb,"Mac");Nb=H(Wb,"Win");Ob=H(Wb,"Linux");Pb=!!Rb()&&H(Rb().appVersion||"","X11")};Xb();
var Yb=Mb,Zb=Nb,$b=Ob,ac=function(){var a="",b;if(M&&n.opera){var c=n.opera.version;a=typeof c=="function"?c():c}else{if(Tb)b=/rv\:([^\);]+)(\)|;)/;else if(N)b=/MSIE\s+([^\);]+)(\)|;)/;else if(O)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Qb());a=d?d[1]:""}}return a},bc=ac(),cc={},P=function(a){return cc[a]||(cc[a]=Cb(bc,a)>=0)};var dc;var ec=function(a){return ea(a)?document.getElementById(a):a},fc=ec,hc=function(a,b){Gb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in gc)a.setAttribute(gc[d],c);else a[d]=c})},gc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},ic=function(a){var b=a.document;if(O&&!P("500")&&!Ub){if(typeof a.innerHeight==
"undefined")a=window;var c=a.innerHeight,d=a.document.documentElement.scrollHeight;if(a==a.top)if(d<c)c-=15;return new K(a.innerWidth,c)}var e=b.compatMode=="CSS1Compat"&&(!M||M&&P("9.50"))?b.documentElement:b.body;return new K(e.clientWidth,e.clientHeight)},jc=function(a){var b=!O&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new J(b.scrollLeft,b.scrollTop)},lc=function(){return kc(document,arguments)},kc=function(a,b){var c=b[0],d=b[1];if(N&&d&&(d.name||d.type)){var e=["<",c];d.name&&
e.push(' name="',tb(d.name),'"');if(d.type){e.push(' type="',tb(d.type),'"');d=ga(d);delete d.type}e.push(">");c=e.join("")}var f=a.createElement(c);if(d)if(ea(d))f.className=d;else hc(f,d);if(b.length>2){function h(g){if(g)f.appendChild(ea(g)?a.createTextNode(g):g)}for(var j=2;j<b.length;j++){var k=b[j];da(k)&&!(fa(k)&&k.nodeType>0)?Eb(mc(k)?Fb(k):k,h):h(k)}}return f},nc=function(a,b){a.appendChild(b)},oc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):l},pc=function(a,b){var c=b.parentNode;
c&&c.replaceChild(a,b)},qc=O&&P("522"),rc=function(a,b){if(typeof a.contains!="undefined"&&!qc&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},Q=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},mc=function(a){if(a&&typeof a.length=="number")if(fa(a))return typeof a.item=="function"||typeof a.item=="string";else if(o(a)=="function")return typeof a.item==
"function";return m},R=function(a){this.c=a||n.document||document};R.prototype.createElement=function(a){return this.c.createElement(a)};R.prototype.createTextNode=function(a){return this.c.createTextNode(a)};R.prototype.m=function(){return this.c.compatMode=="CSS1Compat"};R.prototype.l=function(){return jc(this.c)};R.prototype.appendChild=nc;R.prototype.removeNode=oc;R.prototype.replaceNode=pc;R.prototype.contains=rc;var sc,tc,uc,vc,wc,xc,yc=function(){xc=wc=vc=uc=tc=sc=m;var a=Qb();if(a)if(a.indexOf("Firefox")!=-1)sc=i;else if(a.indexOf("Camino")!=-1)tc=i;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)uc=i;else if(a.indexOf("Android")!=-1)vc=i;else if(a.indexOf("Chrome")!=-1)wc=i;else if(a.indexOf("Safari")!=-1)xc=i};yc();var zc=function(a,b){var c=Q(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return l},S=function(a,b){return zc(a,b)||(a.currentStyle?a.currentStyle[b]:l)||a.style[b]},Ac=function(a){var b;b=a?a.nodeType==9?a:Q(a):document;if(N&&!(b?new R(Q(b)):dc||(dc=new R)).m())return b.body;return b.documentElement},Bc=function(a){var b=a.getBoundingClientRect();if(N){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;
b.top-=c.documentElement.clientTop+c.body.clientTop}return b},Cc=function(a){if(N)return a.offsetParent;for(var b=Q(a),c=S(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;e&&e!=b;e=e.parentNode){c=S(e,"position");d=d&&c=="static"&&e!=b.documentElement&&e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return l},Dc=function(a){var b,c=Q(a),d=S(a,"position"),e=Tb&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=
c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new J(0,0),h=Ac(c);if(a==h)return f;if(a.getBoundingClientRect){b=Bc(a);var j=(c?new R(Q(c)):dc||(dc=new R)).l();f.x=b.left+j.x;f.y=b.top+j.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var k=c.getBoxObjectFor(h);f.x=b.screenX-k.screenX;f.y=b.screenY-k.screenY}else{var g=a;do{f.x+=g.offsetLeft;f.y+=g.offsetTop;if(g!=a){f.x+=g.clientLeft||0;f.y+=g.clientTop||0}if(O&&S(g,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;
break}g=g.offsetParent}while(g&&g!=a);if(M||O&&d=="absolute")f.y-=c.body.offsetTop;for(g=a;(g=Cc(g))&&g!=c.body&&g!=h;){f.x-=g.scrollLeft;if(!M||g.tagName!="TR")f.y-=g.scrollTop}}return f},Ec=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var h=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return h}},Fc=function(a){var b=Q(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);
c=d.queryCommandValue("FontName")}if(!c){c=S(a,"fontFamily");if(M&&$b)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Ab(c,"\"'")},Gc=function(a){var b=a.match(/[^\d]+$/);return b&&b[0]||l},Hc={cm:1,"in":1,mm:1,pc:1,pt:1},Ic={em:1,ex:1},Jc=function(a){var b=S(a,"fontSize"),c=Gc(b);if(b&&"px"==c)return parseInt(b,10);if(N)if(c in Hc)return Ec(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in Ic){var d=a.parentNode,e=S(d,"fontSize");return Ec(d,
b==e?"1em":b,"left","pixelLeft")}var f=lc("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});nc(a,f);b=f.offsetHeight;oc(f);return b};var T={};function Kc(a){if(a==1)return i;return!T[a]}function U(a,b){if(a)if(b==1)if(T[b])T[b]+=","+a;else T[b]=a;else T[b]=a}function Lc(){var a=[];for(var b in T)a.push(T[b]);return a.join(",")}function Mc(a,b){if(a&&a instanceof Array)for(var c=0;c<a.length;c++)a[c]&&typeof a[c]=="string"&&U(a[c],b)}var Nc=m;
function Oc(a,b){var c="script";Nc=Pc(a,b);if(!Nc)a.google_allow_expandable_ads=m;var d=!Qc();Nc&&d&&b.write("<"+c+' src="http://'+t+'/pagead/expansion_embed.js"></'+c+">");var e=lb(a,b,r("1",0.01)),f=d||e;f&&va("msie")&&!window.opera?b.write("<"+c+' src="http://'+t+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+c+">")}function V(a){return a!=l?'"'+a+'"':'""'}
var Rc=function(a,b,c){var d=c.slice(-1)=="?"?"":"&";return[c,d,a,"=",b.toString()].join("")};function W(a,b){if(a&&b)window.google_ad_url=Rc(a,b,window.google_ad_url)}function Y(a){var b=window,c=za[a]||Aa[a]||Da[a]||l,d=b[a];W(c,d)}function Z(a,b){b!=l&&W(a,u(b))}function $(a){var b=window,c=za[a]||Aa[a]||Da[a]||l,d=b[a];Z(c,d)}
function Sc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){W("u_h",b.height);W("u_w",b.width);W("u_ah",b.availHeight);W("u_aw",b.availWidth);W("u_cd",b.colorDepth)}W("u_tz",d);W("u_his",a.history.length);W("u_java",c);navigator.plugins&&W("u_nplug",navigator.plugins.length);navigator.mimeTypes&&W("u_nmime",navigator.mimeTypes.length)}function Tc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Uc(){var a=N&&P("6"),b=Tb&&P("1.8.1"),c=O&&P("525");if(Zb&&(a||b||c))return i;else if(Yb&&(c||b))return i;else if($b&&b)return i;return m}function Qc(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Pc(a,b){if(a.google_allow_expandable_ads===m||!b.body||a.google_ad_output!="html"||Fa(a,b)||!Vc(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Uc())return m;return i}
function Vc(a){var b=a.google_ad_format;if(v(b))return m;if(ya(a)&&!(b=="468x15_0ads_al"))return m;return i}function Wc(){var a;if(y.google_ad_output=="html"&&!(ya(y)||v(y.google_ad_format))&&Kc(0)){var b=["6083035","6083034"];a=w(b,r("0",0));U(a,0)}return a=="6083035"}
function Xc(a,b){if((a.google_unique_id||0)==0&&a.google_ad_output=="html"&&document.body&&typeof b.body.getBoundingClientRect=="function")return w(["36812001","36812002"],r("0.01",0));return""}
function Yc(a){var b="";if((a.google_unique_id||0)==0&&(a.google_ad_output=="js"||a.google_ad_output=="html")){ya(a)||v(a.google_ad_format)||(b=w(["36813001","36813002","36813003","36813004"],r("0.012",0)));if(b=="")b=w(["36813005","36813006"],r("0.008",0))}return b}
function Zc(a,b){switch(a){case "36813002":b.a(1);b.b(["js"]);break;case "36813003":b.a(1);b.b(["html"]);break;case "36813004":b.a(2);b.b(["html","js"]);break;case "36813006":b.a(0);b.b(["html","js"]);break}}function $c(a){if(a.body)try{return ic(window)}catch(b){return new K(-12245933,-12245933)}else return new K(-1,-1)}
function ad(a,b,c,d){var e=Tc(a);c=Rc("ifi",e,c);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+V(ba(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Nc&&Qc()){var h=a.google_container_id||d||l;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,ba(c),a.google_ad_width,a.google_ad_height,
h)}else{var j='<iframe name="google_ads_frame" width='+V(a.google_ad_width)+" height="+V(a.google_ad_height)+" frameborder="+V(a.google_ad_frameborder)+" src="+V(ba(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?bd(a.google_container_id,b,j):b.write(j)}}function cd(a){bb(a)}
function dd(a,b){var c=aa,d=window.google_ad_format,e=mb(window);window.google_ad_url=v(d)?e+"/pagead/sdo?":Wc()?e+"/pagead/render_iframe_ads.html#":e+"/pagead/ads?";$("google_ad_client");Y("google_ad_host");Y("google_ad_host_tier_id");var f=window.google_num_slots_by_client,h=window.google_num_slots_by_channel,j=window.google_prev_ad_formats_by_region,k=window.google_prev_ad_slotnames_by_region,g=window.google_ad_section;if(v(d)){window.google_num_sdo_slots+=1;if(window.google_num_sdo_slots>4)return m}else if(ya(window)){window.google_num_0ad_slots+=
1;if(window.google_num_0ad_slots>3)return m}else{window.google_num_ad_slots+=1;if(window.google_num_slots_to_rotate){Ya(1);j[g]=l;k[g]=l;if(window.google_num_slot_to_show==l)window.google_num_slot_to_show=c%window.google_num_slots_to_rotate+1;if(window.google_num_slot_to_show!=window.google_num_ad_slots)return m}else if(window.google_num_ad_slots>6&&g=="")return m}W("dt",aa);Y("google_language");Y("google_country");Y("google_region");$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");
Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");if(f[A])f[A]+=1;else{f[A]=1;f.length+=1}if(j[g])if(!v(d)){Z("prev_fmts",j[g].toLowerCase());f.length>1&&W("slot",f[A])}k[g]&&Z("prev_slotnames",k[g].toLowerCase());if(d)v(d)||(j[g]=j[g]?j[g]+","+d:d);else if(window.google_ad_slot)k[g]=k[g]?k[g]+","+window.google_ad_slot:window.google_ad_slot;Y("google_max_num_ads");$("google_ad_output");Y("google_adtest");Y("google_ad_callback");
$("google_ad_format");Y("google_ad_slot");Z("correlator",window.google_correlator);window.google_new_domain_checked==1&&window.google_new_domain_enabled==0&&W("dblk",1);$("google_ad_channel");if(window.google_ad_channel){for(var z="",E=window.google_ad_channel.split(ed),B=0;B<E.length;B++){var X=E[B];if(h[X])z+=X+"+";else h[X]=1}Z("pv_ch",z)}$("google_ad_host_channel");if(window.google_ad_host_channel){var qa=fd(window.google_ad_host_channel,window.google_viewed_host_channels);Z("pv_h_ch",qa)}$("google_page_url");
$("google_color_bg");$("google_color_text");$("google_color_link");$("google_color_url");$("google_color_border");$("google_color_line");window.google_reuse_colors?W("reuse_colors",1):W("reuse_colors",0);Y("google_font_face");Y("google_font_size");Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");
Y("google_ad_section");Mc(window.google_eids,1);var Ba;if(Kc(0)){Ba=w(["36814001","36814002"],r("0.005",0));U(Ba,0)}Z("eid",Lc());var wb=window.google_allow_expandable_ads;if(wb!=l)wb?W("ea","1"):W("ea","0");Ra&&W("cb",1);Sa&&W("cd",1);Y("google_feedback");$("google_referrer_url");$("google_page_location");W("frm",window.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");
Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_ui_version");$("google_tag_info");$("google_only_ads_with_video");$("google_only_pyv_ads");$("google_with_pyv_ads");$("google_disable_video_autoplay");var xb=m;if(a){Z("dff",Fc(a));Z("dfs",Jc(a));var x;if(b)if(typeof a.getBoundingClientRect=="function"){var yb=a.getBoundingClientRect();x={x:yb.left,y:yb.top}}else{x=
{};x.x="-252738";x.y="-252738"}else try{x=Dc(a)}catch(wd){x={};x.x="-252738";x.y="-252738"}if(x){xb=i;Z("adx",x.x);Z("ady",x.y)}}if(xb||Ba=="36814002"){var Ca=$c(document);if(Ca){Z("biw",Ca.width);Z("bih",Ca.height)}}var ha=fb();W("ga_vid",ha.vid);W("ga_sid",ha.sid);W("ga_hid",ha.hid);W("ga_fc",ha.from_cookie);Z("ga_wpids",window.google_analytics_uacct);Y("google_ad_override");Y("google_flash_version");W("w",window.google_ad_width||-1);W("h",window.google_ad_height||-1);Sc(window);W("fu",Xa);return i}
function fd(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var h=c[f].split(ed);b[f]||(b[f]={});for(var j="",k=0;k<h.length;k++){var g=h[k];if(!(g==""))if(b[f][g])j+="+"+g;else b[f][g]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var z="";if(d>-1){for(f=0;f<d;f++)z+=e[f]+"|";z+=e[d]}return z}
function gd(){var a=Db(),b=window.google_enable_osd,c="";if(b===i){c="36813006";Zc(c,a)}else if(b!==m&&Kc(0)){c=w(["68120011","68120021","68120031","68120041"],r("0",0));if(c==""){c=Xc(window,document);if(c==""){c=Yc(window);c!=""&&Zc(c,a)}}}U(c,0);var d=m,e=m,f=m;switch(c){case "68120031":f=i;case "68120021":e=i;case "68120041":d=i;break;case "36812002":if(!window.google_atf_included){window.google_atf_included=i;ta("http://"+t+"/pagead/atf.js")}break}var h;if(d){var j=
"google_temp_span";h=window.google_container_id&&fc(window.google_container_id)||fc(j);if(!h&&!window.google_container_id){document.write("<span id="+j+"></span>");h=fc(j)}}var k=m;k=e?dd(h,f):dd();h&&h.id==j&&oc(h);if(k){a.q(window.google_ad_output,window.google_ad_url);ad(window,document,window.google_ad_url);cd(window)}}function hd(a,b,c,d){var e=Wa(a,b,c,d);Oc(window,document);return e}function id(){ab()}
function jd(a){for(var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(h){}}return b}function kd(){var a=window,b=jd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function bd(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var ed=/[+, ]/;window.google_render_ad=gd;var ld=["30143070","30143071","30143075"],md=typeof window.postMessage=="function"||typeof window.postMessage=="object"||typeof document.postMessage=="function",od=function(a,b){typeof A1_googleCreateSlot=="function"?A1_googleCreateSlot(a.google_ad_client):nd(a,b)},qd=function(){if(!pd())return m;return i},rd=function(a){if(v(a.google_ad_format))return m;var b=a.google_ad_output;if(b&&b!="html")return m;var c=a.google_ad_client;if(typeof c!="string"||c.substring(0,4)!="pub-"&&c.substring(0,7)!="ca-pub-")return m;
return i},td=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=r("0.001",0);a.google_a1_eid=sd(ld,b);return a.google_a1_eid},nd=function(a,b){if(!a.google_included_a1_script){var c="script",d="/pagead/show_ads_sra3.js?v\x3d1";b.write("<"+c+' src="http://'+t+d+'"></'+c+">");a.google_included_a1_script=i}},pd=function(){if(N&&P("8"))return m;return md||!O},sd=function(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};function ud(){kd();Ua("show_ads.google_init_globals",hd,id);Oc(window,document)}function vd(){if(!qd(window)||!rd(window))ud();else if(Ta&&window.google_use_a1===i)od(window,document);else{var a=td(window);if(a){U(a,0);window.google_allow_expandable_ads=m}!a||a=="30143070"?ud():od(window,document)}}Ua("show_ads.main",Wa,vd);
})()
