(function(){
var g=false,h=null,k=true,m=(new Date).getTime();var aa={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ba={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},ca={google_only_pyv_ads:"pyv"};function o(a){return aa[a]||ba[a]||ca[a]||h};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function p(){this.b=this.p();this.h=g;if(!this.b)this.h=this.j()}p.prototype.f="__gads=";p.prototype.c="GoogleAdServingTest=";p.prototype.o=function(){return this.b};p.prototype.setCookieInfo=function(a){this.a=a._cookies_[0];if(this.a!=h){this.b=this.a._value_;this.q()}};p.prototype.l=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
p.prototype.k=function(a){if(!(this.b!=h||!this.h)){var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+r(a)+"&domain="+r(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};p.prototype.j=function(){document.cookie=this.c+"Good";var a=this.g(this.c),b=a=="Good";if(b){var c=this.l(-1);document.cookie=this.c+"; expires="+c.toGMTString()}return b};p.prototype.p=function(){var a=this.g(this.f);return a};
p.prototype.g=function(a){var b=document.cookie,c=b.indexOf(a),d=h;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};p.prototype.q=function(){if(!(this.a==h))if(!(this.b==h)){var a=new Date;a.setTime(1000*this.a._expires_);var b=this.a._domain_,c=this.f+this.b+"; expires="+a.toGMTString()+"; path="+this.a._path_+"; domain=."+b;document.cookie=c}};function s(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function da(a,b){if(a=="true")return k;if(a=="false")return g;return b}
function ea(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;for(;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b.toString()}else if(fa()){var c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(i){}}if(c!=h){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var t=this,w=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]")return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};var ga=function(a){var b=w(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var ha=function(a){var b=w(a);return b=="object"||b=="array"||b=="function"},ia=function(a){var b=w(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=ia(a[d]);return c}return a},ja=Date.now||function(){return(new Date).getTime()};var ka=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a,f=0;for(;f<d;f++)f in e&&b.call(c,e[f],f,a)}},pa=function(a){if(w(a)=="array")return a.concat();else{var b=[],c=0,d=a.length;for(;c<d;c++)b[c]=a[c];return b}};var x=function(a,b){this.x=typeof a!="undefined"?a:0;this.y=typeof b!="undefined"?b:0};x.prototype.clone=function(){return new x(this.x,this.y)};x.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var y=function(a,b){this.width=a;this.height=b};y.prototype.clone=function(){return new y(this.width,this.height)};y.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};y.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};y.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
y.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};y.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var qa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var ra=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},xa=function(a,b){if(b)return a.replace(sa,"&amp;").replace(ta,"&lt;").replace(ua,"&gt;").replace(va,"&quot;");else{if(!wa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(sa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ta,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(ua,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(va,"&quot;");return a}},sa=/&/g,ta=/</g,ua=/>/g,va=/\"/g,wa=/[&<>\"]/,ya=function(a,b){var c=b.length,d=0;for(;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var za=function(a,b){var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),i=0;for(;c==0&&i<f;i++){var j=d[i]||"",n=e[i]||"",l=new RegExp("(\\d*)(\\D*)","g"),u=new RegExp("(\\d*)(\\D*)","g");do{var v=l.exec(j)||["","",""],q=u.exec(n)||["","",""];if(v[0].length==0&&q[0].length==0)break;var E=v[1].length==0?0:parseInt(v[1],10),T=q[1].length==0?0:parseInt(q[1],10);c=z(E,T)||z(v[2].length==0,q[2].length==0)||z(v[2],q[2])}while(c==0)}return c},z=function(a,b){if(a<
b)return-1;else if(a>b)return 1;return 0};ja();var A,Aa,B,Ba,Ca,Da,Ea,Fa,Ga,Ha=function(){return t.navigator?t.navigator.userAgent:h};var Ia=function(){Da=Ca=Ba=B=Aa=A=g;var a;if(a=Ha()){var b=t.navigator;A=a.indexOf("Opera")==0;Aa=!A&&a.indexOf("MSIE")!=-1;Ba=(B=!A&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Da=(Ca=!A&&!B&&b.product=="Gecko")&&b.vendor=="Camino"}};Ia();
var C=A,D=Aa,F=Ca,G=B,Ja=Ba,Ka=function(){var a=t.navigator;return a&&a.platform||""},La=Ka(),Ma=function(){Ea=La.indexOf("Mac")!=-1;Fa=La.indexOf("Win")!=-1;Ga=La.indexOf("Linux")!=-1};Ma();var Na=Ea,Oa=Fa,Pa=Ga,Qa=function(){var a="",b;if(C&&t.opera){var c=t.opera.version;a=typeof c=="function"?c():c}else{if(F)b=/rv\:([^\);]+)(\)|;)/;else if(D)b=/MSIE\s+([^\);]+)(\)|;)/;else if(G)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Ha());a=d?d[1]:""}}return a},Ra=Qa();var H=function(a){return za(Ra,a)>=0};var I;var Sa=function(a){return a?new J(K(a)):I||(I=new J)};
var Ta=function(a){return typeof a=="string"?document.getElementById(a):a},Ua=Ta,Wa=function(a,b){qa(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Va)a.setAttribute(Va[d],c);else a[d]=c})},Va={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Xa=function(a){var b=a||t||window,c=b.document;
if(G&&!H("500")&&!Ja){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new y(b.innerWidth,d)}var f=Sa(c),i=f.e()&&(!C||C&&H("9.50"))?c.documentElement:c.body;return new y(i.clientWidth,i.clientHeight)},Ya=function(){var a=I||(I=new J);return a.i.apply(a,arguments)},Za=function(a,b){a.appendChild(b)},$a=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):h},cb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,
b)};
var db=G&&za(Ra,"521")<=0,eb=function(a,b){if(typeof a.contains!="undefined"&&!db&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},K=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},fb=function(a){if(a&&typeof a.length=="number")if(ha(a))return typeof a.item=="function"||typeof a.item=="string";else if(w(a)=="function")return typeof a.item=="function";return g},
J=function(a){this.d=a||t.document||document};
J.prototype.i=function(a,b){if(D&&b&&(b.name||b.type)){var c=["<",a];b.name&&c.push(' name="',xa(b.name),'"');if(b.type){c.push(' type="',xa(b.type),'"');b=ia(b);delete b.type}c.push(">");a=c.join("")}var d=this.createElement(a);b&&Wa(d,b);if(arguments.length>2){function e(j){if(j)this.appendChild(d,typeof j=="string"?this.createTextNode(j):j)}var f=2;for(;f<arguments.length;f++){var i=arguments[f];ga(i)&&!(ha(i)&&i.nodeType>0)?ka(fb(i)?pa(i):i,e,this):e.call(this,i)}}return d};
J.prototype.createElement=function(a){return this.d.createElement(a)};J.prototype.createTextNode=function(a){return this.d.createTextNode(a)};J.prototype.e=function(){var a=this.d;if(a.compatMode)return a.compatMode=="CSS1Compat";if(G){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return g};
J.prototype.n=function(){var a=this.d;return!G&&this.e()?a.documentElement:a.body};J.prototype.m=function(){var a=this.n();return new x(a.scrollLeft,a.scrollTop)};J.prototype.appendChild=Za;J.prototype.removeNode=$a;J.prototype.replaceNode=cb;J.prototype.contains=eb;var gb,hb,ib,jb,kb,lb,mb=function(){lb=kb=jb=ib=hb=gb=g;var a=Ha();if(!!a)if(a.indexOf("Firefox")!=-1)gb=k;else if(a.indexOf("Camino")!=-1)hb=k;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)ib=k;else if(a.indexOf("Android")!=-1)jb=k;else if(a.indexOf("Chrome")!=-1)kb=k;else if(a.indexOf("Safari")!=-1)lb=k};mb();var nb=function(a,b){var c=K(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return h};var L=function(a,b){return nb(a,b)||(a.currentStyle?a.currentStyle[b]:h)||a.style[b]};
var ob=function(a){var b;b=a?a.nodeType==9?a:K(a):document;if(D&&!Sa(b).e())return b.body;return b.documentElement},pb=function(a){var b=a.getBoundingClientRect();if(D){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},qb=function(a){if(D)return a.offsetParent;var b=K(a),c=L(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;for(;e&&e!=b;e=e.parentNode){c=L(e,"position");d=d&&c=="static"&&e!=b.documentElement&&
e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return h},rb=function(a){var b,c=K(a),d=L(a,"position"),e=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new x(0,0),i=ob(c);if(a==i)return f;if(a.getBoundingClientRect){b=pb(a);var j=Sa(c).m();f.x=b.left+j.x;f.y=b.top+j.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var n=c.getBoxObjectFor(i);f.x=b.screenX-
n.screenX;f.y=b.screenY-n.screenY}else{var l=a;do{f.x+=l.offsetLeft;f.y+=l.offsetTop;if(l!=a){f.x+=l.clientLeft||0;f.y+=l.clientTop||0}if(G&&L(l,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}l=l.offsetParent}while(l&&l!=a);if(C||G&&d=="absolute")f.y-=c.body.offsetTop;l=a;for(;(l=qb(l))&&l!=c.body;){f.x-=l.scrollLeft;if(!C||l.tagName!="TR")f.y-=l.scrollTop}}return f};F&&H("1.9");
var sb=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var i=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return i}},tb=function(a){var b=K(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=L(a,"fontFamily");if(C&&Pa)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return ya(c,"\"'")},ub=function(a){var b=
a.match(/[^\d]+$/);return b&&b[0]||h},vb={cm:1,"in":1,mm:1,pc:1,pt:1},wb={em:1,ex:1},xb=function(a){var b=L(a,"fontSize"),c=ub(b);if(b&&"px"==c)return parseInt(b,10);if(D)if(c in vb)return sb(a,b,"left","pixelLeft");else if(a.parentNode&&c in wb)return sb(a.parentNode,b,"left","pixelLeft");var d=Ya("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Za(a,d);b=d.offsetHeight;$a(d);return b};var M=document,O=navigator,P=window;
function yb(){var a=M.cookie,b=Math.round((new Date).getTime()/1000),c=P.google_analytics_domain_name,d=typeof c=="undefined"?zb("auto"):zb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,i=a.indexOf("__utmc="+d)>-1,j,n={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");n.sid=f&&i?j[3]+"":P&&P.gaGlobal&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";n.vid=j[0]+"."+j[1];n.from_cookie=k}else{n.sid=P&&P.gaGlobal&&P.gaGlobal.sid?P.gaGlobal.sid:b+"";n.vid=P&&P.gaGlobal&&P.gaGlobal.vid?
P.gaGlobal.vid:(Ab()^Bb()&2147483647)+"."+b;n.from_cookie=g}n.dh=d;n.hid=P&&P.gaGlobal&&P.gaGlobal.hid?P.gaGlobal.hid:Ab();return P.gaGlobal=n}function Ab(){return Math.round(Math.random()*2147483647)}
function Bb(){var a=M.cookie?M.cookie:"",b=P.history.length,c,d,e=[O.appName,O.version,O.language?O.language:O.browserLanguage,O.platform,O.userAgent,O.javaEnabled()?1:0].join("");if(P.screen)e+=P.screen.width+"x"+P.screen.height+P.screen.colorDepth;else if(P.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=M.referrer?M.referrer:"";c=e.length;for(;b>0;)e+=b--^c++;return Cb(e)}
function Cb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;d=a.length-1;for(;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function zb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=M.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Cb(a.toLowerCase())};var Q="";function Db(a){if(a){if(Q!="")Q+=",";Q+=a}}var R=g,Eb=da("true",g);function Fb(a,b){var c="script";R=Gb(a,b);var d=!Hb();R&&d&&b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/expansion_embed.js"></'+c+">");var e=Ib(a,b,s("1",0.01)),f=d||e;f&&fa()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}
function S(a){return a!=h?'"'+a+'"':'""'}function r(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function U(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function V(a){var b=window,c=o(a),d=b[a];U(c,d)}function W(a,b){b!=h&&U(a,r(b))}function X(a){var b=window,c=o(a),d=b[a];W(c,d)}function Y(a,b){var c=window,d=o(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];U(d,e)}
function Jb(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){U("u_h",b.height);U("u_w",b.width);U("u_ah",b.availHeight);U("u_aw",b.availWidth);U("u_cd",b.colorDepth)}U("u_tz",d);U("u_his",history.length);U("u_java",c);navigator.plugins&&U("u_nplug",navigator.plugins.length);navigator.mimeTypes&&U("u_nmime",navigator.mimeTypes.length)}
function Kb(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==h)a._GA_googleCookieHelper=new p;if(!a._google_cookie_fetched){a._google_cookie_fetched=k;a._GA_googleCookieHelper.k(Lb(a.google_ad_client))}}}function Lb(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Mb(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function Nb(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Ob(){var a=D&&H("6")&&!H("8"),b=F&&H("1.8.1"),c=G&&H("525");if(Oa&&(a||b||c))return k;else if(Na&&(c||b))return k;else if(Pa&&b)return k;return g}function Hb(){return typeof ExpandableAdSlotFactory=="function"&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Gb(a,b){var c=a.google_allow_expandable_ads;if(c!=h&&c==g||!b.body||a.google_ad_output!="html"||Pb(a,b)||Qb(a)||Z(a.google_ad_format)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Ob())return g;return k}
function Rb(){var a=Math.random(),b=s("0",0.03),c=2*b;if(a<b)return"30143019";if(a<c)return"30143020";return""}function Sb(){var a=Math.random(),b=s("0",0.03),c=2*b;if(a<b)return"30143021";if(a<c)return"30143022";return""}function Tb(){var a=Math.random(),b=s("0.03",0.02),c=2*b;if(a<b)return"6083028";if(a<c)return"6083029";return""}function Ub(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}
function Vb(a,b,c,d){var e=Nb(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+S($(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Wb(a)&&Hb()){var i=a.google_container_id||d||h;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,$(c),a.google_ad_width,a.google_ad_height,
i)}else{var j='<iframe name="google_ads_frame" width='+S(a.google_ad_width)+" height="+S(a.google_ad_height)+" frameborder="+S(a.google_ad_frameborder)+" src="+S($(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';j=Xb(a.google_ad_width,a.google_ad_height,j);a.google_container_id?Yb(a.google_container_id,b,j):b.write(j)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+S($(c))+"></"+f+">")}
function Wb(a){if(!R)return g;var b=Q.indexOf("30143020")!=-1,c=Q.indexOf("30143019")!=-1,d=a.google_expandable_iframe;return Eb&&!c||b||d}function Zb(a){var b=da("false",g);return b&&a.indexOf("30143021")==-1||a.indexOf("30143022")!=-1}
function Xb(a,b,c){var d=Zb(Q);if(R&&d){var e="border:none;height:"+b+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";return'<ins style="display:inline-table;'+e+'"><ins style="display:block;'+e+'">'+c+"</ins></ins>"}return c}function $b(a,b,c){if(!a)return g;if(!b)return k;return c}
function ac(a){for(var b in aa)a[b]=h;for(var b in ba)b=="google_correlator"||(a[b]=h);for(var b in ca)a[b]=h;a.google_allow_expandable_ads=h;a.google_container_id=h;a.google_expandable_iframe=h;a.google_tag_info=h}function Qb(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Z(a){return a&&a.indexOf("_sdo")!=-1}
function bc(a){var b=h,c=window,d=document,e=m,f=c.google_ad_format,i=cc(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=i+"/cpa/ads?";j=escape(Lb(c.google_ad_client));c.google_ad_region="_google_cpa_region_";V("google_cpa_choice");if(typeof d.characterSet!="undefined")W("oe",d.characterSet);else typeof d.charset!="undefined"&&W("oe",d.charset)}else if(Z(f)){c.google_ad_url=i+"/pagead/sdo?";j=escape(Mb(c.google_ad_client))}else{c.google_ad_url=i+"/pagead/ads?";j=escape(Lb(c.google_ad_client))}c.google_ad_url+=
"client="+j;V("google_ad_host");V("google_ad_host_tier_id");var n=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,u=c.google_prev_ad_formats_by_region,v=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(Z(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Qb(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){u[q]=b;v[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}U("dt",m);V("google_language");c.google_country?V("google_country"):V("google_gl");V("google_region");
X("google_city");X("google_hints");V("google_safe");V("google_encoding");V("google_last_modified_time");X("google_alternate_ad_url");V("google_alternate_color");V("google_skip");V("google_targeting");var E=c.google_ad_client;if(n[E])n[E]+=1;else{n[E]=1;n.length+=1}if(u[q])if(!Z(f)){W("prev_fmts",u[q].toLowerCase());n.length>1&&U("slot",n[E])}v[q]&&W("prev_slotnames",v[q].toLowerCase());if($b(f,c.google_ad_slot,c.google_override_format)){W("format",f.toLowerCase());Z(f)||(u[q]=u[q]?u[q]+","+f:f)}else if(c.google_ad_slot)v[q]=
v[q]?v[q]+","+c.google_ad_slot:c.google_ad_slot;V("google_max_num_ads");U("output",c.google_ad_output);V("google_adtest");V("google_ad_callback");V("google_ad_slot");X("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&U("dblk",1);if(c.google_ad_channel){X("google_ad_channel");var T="",ab=c.google_ad_channel.split(dc),la=0;for(;la<ab.length;la++){var ma=ab[la];if(l[ma])T+=ma+"+";else l[ma]=1}W("pv_ch",T)}if(c.google_ad_host_channel){X("google_ad_host_channel");var lc=
ec(c.google_ad_host_channel,c.google_viewed_host_channels);W("pv_h_ch",lc)}c.google_enable_first_party_cookie&&W("cookie",c._GA_googleCookieHelper.o());X("google_page_url");Y("google_color_bg",e);Y("google_color_text",e);Y("google_color_link",e);Y("google_color_url",e);Y("google_color_border",e);Y("google_color_line",e);c.google_reuse_colors?U("reuse_colors",1):U("reuse_colors",0);V("google_font_face");V("google_kw_type");X("google_kw");X("google_contents");V("google_num_radlinks");V("google_max_radlink_len");
V("google_rl_filtering");V("google_rl_mode");V("google_rt");X("google_rl_dest_url");V("google_num_radlinks_per_unit");V("google_ad_type");V("google_image_size");V("google_ad_region");if(R)if(c.google_expandable_iframe===g)Ub(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=k;else{if(!(c.google_expandable_iframe==k)){var N=Rb();Db(N);if(N=="30143019"||N==""&&!Eb)Ub(c);if(!N){N=Sb();Db(N)}}}else Ub(c);
W("eid",Q);var bb=c.google_allow_expandable_ads;if(bb!=h)bb?U("ea","1"):U("ea","0");V("google_feedback");X("google_referrer_url");X("google_page_location");U("frm",c.google_iframing);V("google_bid");V("google_ctr_threshold");V("google_cust_age");V("google_cust_gender");V("google_cust_interests");V("google_cust_id");V("google_cust_job");V("google_cust_u_url");V("google_cust_l");V("google_cust_lh");V("google_cust_ch");V("google_ed");V("google_video_doc_id");V("google_video_product_type");X("google_ui_features");
X("google_ui_version");X("google_tag_info");X("google_only_ads_with_video");X("google_only_pyv_ads");X("google_disable_video_autoplay");if(a){W("ff",tb(a));W("fs",xb(a));var na=rb(a),oa=Xa();if(na&&oa){W("biw",oa.width);W("bih",oa.height);W("adx",na.x);W("ady",na.y)}}yb();U("ga_vid",c.gaGlobal.vid);U("ga_sid",c.gaGlobal.sid);U("ga_hid",c.gaGlobal.hid);U("ga_fc",c.gaGlobal.from_cookie);X("google_analytics_uacct");V("google_ad_override");V("google_flash_version");Jb(c);return k}
function ec(a,b){var c=a.split("|"),d=-1,e=[],f=0;for(;f<c.length;f++){var i=c[f].split(dc);b[f]||(b[f]={});var j="",n=0;for(;n<i.length;n++){var l=i[n];if(!(l==""))if(b[f][l])j+="+"+l;else b[f][l]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var u="";if(d>-1){var f=0;for(;f<d;f++)u+=e[f]+"|";u+=e[d]}return u}
function fc(){var a=window,b=document;Kb(a);var c=Tb();Db(c);var d;if(c=="6083029"){var e="google_temp_span";d=a.google_container_id&&Ua(a.google_container_id)||Ua(e);if(!d&&!a.google_container_id){b.write("<span id="+e+"></span>");d=Ua(e)}}var f=bc(d);d&&d.id==e&&$a(d);if(!!f){Vb(a,b,a.google_ad_url);ac(a)}}function $(a){var b=(new Date).getTime()-m,c="&dtd="+(b<1000?b:"M");return a+c}function gc(){fc();return k}
function Pb(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return k}
function hc(a){var b=window,c=h,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Z(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;ic(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=m;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ea();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function jc(a){if(a in kc)return kc[a];return kc[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var kc={};function fa(){return jc("msie")&&!window.opera}
function mc(a){var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;for(;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(i){}}return b}function nc(){var a=window,b=mc(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function oc(a,b){for(var c in b)a["google_"+c]=b[c]}
function pc(a,b){if(!b)return a.location;return a.referrer}function qc(a,b){if(!b&&a.google_referrer_url==h)return"0";else if(b&&a.google_referrer_url==h)return"1";else if(!b&&a.google_referrer_url!=h)return"2";else if(b&&a.google_referrer_url!=h)return"3";return"4"}function rc(a,b,c,d){a.page_url=pc(c,d);a.page_location=h}function sc(a,b,c,d){a.page_url=b.google_page_url;a.page_location=pc(c,d)||"EMPTY"}
function tc(a,b){var c={},d=Pb(a,b);c.iframing=qc(a,d);!!a.google_page_url?sc(c,a,b,d):rc(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:h;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function uc(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=h;b.page_url=c;b.page_location=a.location;b.last_modified_time=h;b.referrer_url=c;return b}
function ic(a,b){var c;c=a.google_page_url==h&&vc[b.domain]?uc(b):tc(a,b);oc(a,c)}function Yb(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var vc={};vc["ad.yieldmanager.com"]=k;var dc=/[+, ]/;window.google_render_ad=fc;var wc={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function xc(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in wc;if(e.length>=2)f=f||e[e.length-2]in wc;return f}
function Ib(a,b,c){if(xc(a)){a.google_new_domain_checked=1;return g}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return k}}return g}function cc(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!xc(a)&&a.google_new_domain_enabled==1)return b;return c};nc();hc(gc);Fb(window,document);
})()
