(function(){
var e=true,g=null,h=false,i=navigator,aa=undefined,ba=encodeURIComponent,j=parseInt,k=window,m=document,n=Math;function ca(a,b){return a.toString=b}
var o="push",p="toString",q="valueOf",t="length",da="plugins",u="prototype",ea="round",v="slice",w="replace",x="document",z="split",fa="cookie",ga="charAt",A="userAgent",B="screen",C="indexOf",ha="domain",D="write",E="call",ia="random",F="getParameter",ja="referrer",G="substring",ka="apply",la="contentWindow",H="getTime",I="join",ma="toLowerCase",na=this,oa=function(a,b,c){a=a[z](".");c=c||na;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[t]&&(d=a.shift());)if(!a[t]&&b!==aa)c[d]=
b;else c=c[d]?c[d]:(c[d]={})};n.floor(n[ia]()*2147483648)[p](36);var pa=function(a,b){var c=a.Y;if(arguments[t]>2){var d=Array[u][v][E](arguments,2);c&&d.unshift[ka](d,c);c=d}b=a.$||b;a=a.Z||a;var f=b||na;d=c?function(){var l=Array[u][v][E](arguments);l.unshift[ka](l,c);return a[ka](f,l)}:function(){return a[ka](f,arguments)};d.Y=c;d.$=b;d.Z=a;return d},J=function(a,b,c){oa(a,b,c)},qa=function(a,b){function c(){}c.prototype=b[u];a.la=b[u];a.prototype=new c};function ra(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a}function sa(a,b){if(a=="true")return e;if(a=="false")return h;return b}function K(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ta="pagead2.googlesyndication.com",ua="googleads.g.doubleclick.net",va="pubads.g.doubleclick.net",wa="securepubads.g.doubleclick.net",xa="partner.googleadservices.com",ya=K("pagead2.googlesyndication.com",ta);K("googleads.g.doubleclick.net",ua);K("pagead2.googlesyndication.com",ta);var za=K("pubads.g.doubleclick.net",va),Aa=K("partner.googleadservices.com",xa),Ba=K("securepubads.g.doubleclick.net",wa);function L(a){return typeof ba=="function"?ba(a):escape(a)}function Ca(a){if(a in Da)return Da[a];return Da[a]=i[A][ma]()[C](a)!=-1}var Da={};function Ea(){return Ca("msie")&&!k.opera}
function Fa(){if(i[da]&&i.mimeTypes[t]){var a=i[da]["Shockwave Flash"];if(a&&a.description)return a.description[w](/([a-zA-Z]|\s)+/,"")[w](/(\s)+r/,".")}else if(i[A]&&i[A][C]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[p]()}else if(Ea()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(f){if(a==
6)return a[p]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(l){}}if(b){a=b.GetVariable("$version")[z](" ")[1];return a[w](/,/g,".")}}return"0"}var Ha=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=k.history[t];a.u_java=i.javaEnabled();if(k[B]){a.u_h=k[B].height;a.u_w=k[B].width;a.u_ah=k[B].availHeight;a.u_aw=k[B].availWidth;a.u_cd=k[B].colorDepth}if(i[da])a.u_nplug=i[da][t];if(i.mimeTypes)a.u_nmime=i.mimeTypes[t]};var Ia={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ja={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Ka=
{google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var La=m,M=i,N=k;
function Ma(){var a=La[fa],b=n[ea]((new Date)[H]()/1000),c=N.google_analytics_domain_name;c=typeof c=="undefined"?Na("auto"):Na(c);var d=a[C]("__utma="+c+".")>-1,f=a[C]("__utmb="+c)>-1,l=a[C]("__utmc="+c)>-1,r={},s=!!N&&!!N.gaGlobal;if(d){a=a[z]("__utma="+c+".")[1][z](";")[0][z](".");r.sid=f&&l?a[3]+"":s&&N.gaGlobal.sid?N.gaGlobal.sid:b+"";r.vid=a[0]+"."+a[1];r.from_cookie=e}else{r.sid=s&&N.gaGlobal.sid?N.gaGlobal.sid:b+"";r.vid=s&&N.gaGlobal.vid?N.gaGlobal.vid:(n[ea](n[ia]()*2147483647)^Oa()&2147483647)+
"."+b;r.from_cookie=h}r.dh=c;r.hid=s&&N.gaGlobal.hid?N.gaGlobal.hid:n[ea](n[ia]()*2147483647);return N.gaGlobal=r}function Oa(){var a=La[fa]?La[fa]:"",b=N.history[t],c,d=[M.appName,M.version,M.language?M.language:M.browserLanguage,M.platform,M[A],M.javaEnabled()?1:0][I]("");if(N[B])d+=N[B].width+"x"+N[B].height+N[B].colorDepth;else if(N.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[B].width+"x"+c[B].height}d+=a;d+=La[ja]?La[ja]:"";for(a=d[t];b>0;)d+=b--^a++;return Pa(d)}
function Pa(a){var b=1,c=0,d;if(!(a==aa||a=="")){b=0;for(d=a[t]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Na(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=La[ha];if("www."==a[G](0,4))a=a[G](4,a[t])}return Pa(a[ma]())};m.URL&&(m.URL[C]("?google_debug")>0||m.URL[C]("&google_debug")>0);function Sa(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=m[ha]}ca(Sa[u],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Ta(){this.v=Ua(this);this.L=h;if(!this.v)this.L=Va(this)}Ta[u].K="__gads=";Ta[u].B="GoogleAdServingTest=";Ta[u].setCookieInfo=function(a){this.q=a._cookies_[0];if(this.q!=g){this.v=this.q._value_;Wa(this)}};
var Xa=function(a,b){a=(new Date)[q]();var c=new Date;c.setTime(a+b);return c},Ya=function(a){var b=15552000000;a=Xa(a,b);b="ID=12345:T="+b;var c="/",d=m[ha];return new Sa(b,a[q](),c,d)},Za="http://"+Aa+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",$a=function(a,b){if(!(a.v||!a.L)){a="script";var c=m[ha];b=Za+"&client="+L(b)+"&domain="+L(c);m[D]("<"+a+' src="'+b+'"></'+a+">")}},Va=function(a){m.cookie=a.B+"Good";var b=ab(a,a.B);if(b=b=="Good"){var c=Xa(a,-1);m.cookie=a.B+"; expires="+
c.toGMTString()}return b},Ua=function(a){return a=ab(a,a.K)},ab=function(a,b){a=m[fa];var c=a[C](b),d="";if(c!=-1){b=c+b[t];c=a[C](";",b);if(c==-1)c=a[t];d=a[G](b,c)}return d},Wa=function(a){if(!(a.q==g))if(a.v){var b=new Date;b.setTime(1000*a.q._expires_);var c=a.q._domain_;a=a.K+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;m.cookie=a}};function bb(a,b){try{return a.top[x].URL==b.URL}catch(c){}return h};sa("true",h);sa("false",h);sa("false",h);var cb=sa("false",h),db=k;var eb=function(a){this.X=(this.M=a&&a.GA_jstiming)&&this.M.load};eb[u].tick=function(a,b){this.X.tick(a,b)};eb[u].report=function(a){var b={};b.e=a;this.M.report(this.X,b)};var gb=function(){};qa(gb,eb);gb[u].tick=function(){};gb[u].report=function(){};var hb=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var O=db&&n[ia]()<ra("0.005",0.0010)&&db.GA_jstiming&&db.GA_jstiming.load&&db.location.protocol=="http:"?new eb(db):new gb(db);O.tick("js_load");function Q(a){return typeof a=="function"}function ib(a,b){if(typeof a!="string"||a[t]==0)return g;else if(typeof b!="string"||b[t]==0)return g;return jb(R(),a,b)}J("GA_googleAddSlot",ib);function _GA_googleInitializeAdEngine(a){if(!S()){kb(lb(a));mb(S())}}J("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function nb(){R().ba=e;_GA_googleInitializeAdEngine(g);var a=S().h;a=="sync"||a=="sync_sra"?S().i():ob(R())}J("GA_googleFetchAds",nb);function pb(){_GA_googleInitializeAdEngine("iframe");$a(k._GA_googleCookieHelper,k.GS_googleGetIdsForAdSenseService())}J("GA_googleUseIframeRendering",pb);function qb(){var a=k.GA_googleEnv[F]("google_ad_impl");a==g&&k.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}J("GA_googleUseSyncSRARendering",qb);
function rb(a){if(!(S()==g))if(!(S().h=="iframe")){if(sb(S()))if(S().J){var b=tb(R(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(ub(S(),a)!=g&&!S().k)return;S().n(a)}}J("GA_googleFillSlot",rb);function vb(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(!(S()==g))if(!(S().h!="iframe")){jb(R(),a,b);a=new wb(c,d,h,e);xb(R(),b,a);S().n(b)}}J("GA_googleFillSlotWithSize",vb);function yb(){zb(new Ab(Ia));kb(g)}J("GA_googleResetAll",yb);k.google_noFetch=h;
function Bb(){k.google_noFetch=e}J("GA_googleNoFetch",Bb);function Cb(){k.google_delayFetch=e}J("GA_googleDelayFetch",Cb);function wb(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ca(wb[u],function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Db(a){var b={};a=a[z]("?");a=a[a[t]-1][z]("&");for(var c=0;c<a[t];c++){var d=a[c][z]("=");if(d[0])try{b[d[0][ma]()]=d[t]>1?k.decodeURIComponent?decodeURIComponent(d[1][w](Eb," ")):unescape(d[1]):""}catch(f){}}return b}function Fb(a){a=a||m.URL;this.V=Db(a)}Fb[u].getParameter=function(a){return a==g?g:this.V[a]};Fb[u].setParameter=function(a,b){this.V[a]=b};var Gb=function(a){if(!cb)return a?"http://"+za:"http://"+Aa;return"https://"+Ba};
function Hb(a){return a[w](/&/g,"&amp;")[w](/</g,"&lt;")[w](/>/g,"&gt;")[w](/\"/g,"&quot;")}function Ib(){this.D=g;this.W=h;this.ka=(new Date)[q]()}
var Kb=function(a,b){if(!(a.D!=g))if(!a.W){a.D=k.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.D){var c=a.D[x],d=[];d[o]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[o]("<p>Google Ad Capture Window</p>");
for(var f in b)Q(b[f])||d[o](Jb(a,f,b[f]));d[o]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[o]("<script>displayTime('blocked', pageStartTime);<\/script>");d[o]("<p>Total Page Load Time (ms): <label id='total'></label>");d[o]("</body>\n</html>");a=d[I]("\n");(b=k.GA_googleEnv[F]("google_capture_norender")!=g)?c[D](Hb(a)):c[D](a);c.close()}else a.W=e}},Jb=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";var d="<p>Slot "+b+"</p>";c=c==g||c._html_==
g?"No ad":c._html_;var f="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+f+b};function Lb(a){this.d={};this.C=a}var Mb=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.C)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Nb=function(a,b){for(var c in b.d)Q(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Lb[u].getAttribute=function(a){return this.d[a]};
Lb[u].g=function(){var a=[];for(var b in this.d)if(!Q(this.d[b])){var c=Ia[b]||Ja[b]||Ka[b]||g,d=this.d[b];c&&d&&a[o](c+"="+L(d))}return a[I]("&")};
var Pb=function(a,b,c,d){a=Ob(a,b,c,d);b=[];a[0]&&a[0][t]>0&&b[o](a[0][I]("&"));a[1]&&a[1][t]>0&&b[o]("sps="+a[1][I]("|"));return b[I]("&")},Ob=function(a,b,c,d){var f=[],l=[];b=b.d;for(var r in d)if(!Q(r)){var s=d[r];if(s){var y="";if(b[r]!=g)y=L(b[r]);var Ga=[],P=-1,Qa=-1;for(var Ra in a)if(!Q(a[Ra])){++P;if(c[Ra]==g)Ga[o]("");else{var fb=c[Ra].d;if(fb[r]!=g){Ga[o](L(L(fb[r])));Qa=P}else Ga[o]("")}}if(Qa>=0){P=L(y);y=[];y[o](P);for(P=0;P<=Qa;++P)y[o](Ga[P]);l[o](s+","+y[I](","))}else y&&f[o](s+
"="+y)}}a=[];a[o](f);a[o](l);return a};function Qb(a,b){this.I=a;this.s=b;this.Q=0;this.ha=this.N=this.O=h;this.fa=this.ga=this.S=this.ca=g}var Rb=function(a){a.N=e;a.ca=(new Date)[q]()},Sb=function(a){a.S=(new Date)[q]()},Tb=function(a){a.ha=e;a.ga=(new Date)[q]()},Ub=function(a){a.fa=(new Date)[q]()};ca(Qb[u],function(){return"[GA_GoogleAdSlot: pubid="+this.I+", name="+this.s+", loaded="+this.O+", tries="+this.Q+"]"});
function Ab(a){this.a={};this.c=[];this.r={};this.C=a;this.U=new Lb(this.C);this.A={};this.ba=h;this.o=g}
var jb=function(a,b,c){b=new Qb(b,c);return a.a[b.s]=b},Vb=function(a,b){var c=[];for(var d in a.a)if(!Q(a.a[d])){if(b){var f=tb(a,d);if(f==g||!f._enabled_)continue}f=a.a[d];f.N||c[o](f)}return c},Wb=function(a,b){return Vb(a,b)[t]},Xb=function(a){var b=[];for(var c in a.a){var d=a.a[c];Q(d)||d.N&&d.S==g&&b[o](c)}return b},Yb=function(a){var b=0;for(var c in a.a)if(!Q(a.a[c])){var d=tb(a,c);d!=g&&d._enabled_&&b++}return b},Zb=function(a){for(var b in a.a)if(!Q(a.a[b])){var c=a.a[b];Rb(c)}},$b=function(a,
b){a=a.a[b];Rb(a)},ac=function(a,b){a=a.a[b];Sb(a)},bc=function(a,b){a=a.a[b];Tb(a)},T=function(a,b){b=a.a[b];Ub(b);hb(O,"ga_render",a.c[t],"ga_srt")},cc=function(a){var b=0;for(var c in a.a)Q(a.a[c])||b++;return b};ca(Ab[u],function(){var a="[AdData:",b=[];for(var c in this.a)Q(this.a[c])||b[o](this.a[c][p]());for(var d in this.r)Q(this.r[d])||b[o]("["+d+","+this.r[d]+"]");a+=b[I]();a+="]";return a});
var dc=function(a,b){return a.a[b]},ec=function(a,b,c){if(!(b==g||b[t]==0)){if(c==g||c[t]==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function fc(a,b){ec(R(),a,b)}J("GA_googleAddAttr",fc);var gc=function(a,b,c){Mb(a.U,b,c)};function hc(a,b){gc(R(),a,b)}J("GA_googleAddAdSensePageAttr",hc);var ic=function(a){return a.U},jc=function(a,b,c,d){if(!(b==g||b[t]==0)){if(S()==g||S().h!="iframe"){var f=a.a[b];if(f==g)return}f=a.A[b];if(f==g)a.A[b]=new Lb(a.C);Mb(a.A[b],c,d)}};
function kc(a,b,c){jc(R(),a,b,c)}J("GA_googleAddAdSenseSlotAttr",kc);var lc=function(a,b){return a.A[b]},mc=function(a){a=Gb(a.google_new_gam_domain_enabled);return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},ob=function(a){if(a.o!=g)S().i();else{var b=[];for(var c in a.a)Q(a.a[c])||b[o](c);a=k.GS_googleGetIdsForAdSenseService();b=mc(k)+"&client="+escape(a)+"&page_slots="+escape(b[I]());m[D]("<script src = '"+b+"'><\/script>")}};
Ab[u].setAdSlotAttributes=function(a){this.o=a;S().J=e;S().i()};function nc(a){R().setAdSlotAttributes(a)}J("GA_googleSetAdSlotAttributes",nc);var xb=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;S().J=e},tb=function(a,b){return a.o!=g?a.o[b]:g};function oc(a,b){this.ma=a;this.aa=b}function pc(a,b){this.AdSlotContent=oc;this.AdSlotConent(pc.HTML_TYPE,a);this._html_=b}ca(pc[u],function(){return"[GA_HTMLAdSlotContent expandable="+this.aa+", html="+this._html_+"]"});pc.prototype=new oc(pc.HTML_TYPE,h);
function qc(a,b,c){if(!c||c<0||c>1)c=0;this.ia=n[ia]()<c;this.da=a;this.R=b+"/pagead/gen_204?id="+L(a);this.ea=[]}var U=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.R+="&"+b+"="+L(c)},rc=function(a){var b=R();for(var c in b.a){var d=b.a[c];if(!Q(d)&&d.I!=g){U(a,"pub_id",d.I);break}}U(a,"nslots",cc(b)[p]());U(a,"pub_url",m.URL);U(a,"pub_ref",m[ja])},sc=function(a){if(!a.ia||!a.da||!a.R)return h;var b=new Image;b.src=a.R;a.ea[o](b);return e};
function V(a){this.f=g;this.o={};this.p=this.b="";this.k=a;this.l=this.H=this.t=h;this.h="sync";this.ja=Ia;this.u=e;this.J=h;this.P=k.google_new_gam_domain_enabled}
var mb=function(a){a.t=k.GA_googleEnv[F]("google_nofetch")!=g||k.google_noFetch;a.H=k.GA_googleEnv[F]("google_norender")!=g;a.l=k.GA_googleEnv[F]("google_capture")!=g||k.GA_googleEnv[F]("google_capture_norender")!=g;if(a.l)a.H=e;tc(a,k);a.b=a.p;var b=pa(a.T,a);uc(a,k,b)},uc=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return e}if(b.addEventListener){b.addEventListener("load",c,h);return e}return h};V[u].F=function(){this.l&&Kb(k.GA_googleAdCapture,this.f)};
var vc=function(a){if(a.h=="sync_sra"){var b=R(),c=cc(b);b=b.c[t];if(c!=b){a.G=new qc("sra_mismatch",Gb(a.P),ra("0.001",0.0010));U(a.G,"correlator",a.m);U(a.G,"fslots",b[p]());rc(a.G);sc(a.G)}}},wc=function(a){O.tick("ga_onload");O.report(a.h)},xc=function(a){var b=Xb(R());if(b[t]>0){a.z=new qc("missing_cb",Gb(a.P),ra("0.01",0.0010));U(a.z,"pending",b[I]());U(a.z,"correlator",a.m);U(a.z,"impl",a.h);rc(a.z);sc(a.z)}};
V[u].T=function(){wc(this);this.F();vc(this);xc(this)};var tc=function(a){var b=k.GA_googleEnv[F]("google_ad_url");if(b==g||b[t]==0)a.p=Gb(a.P)+"/gampad/ads?";else{if(b[ga](b[t]-1)!="?")b+="?";a.p=b}};V[u].j=function(){};
var ub=function(a,b){return a.f!=g?a.f[b]:g},yc=function(){var a=i[A],b=a[C]("MSIE ");return b==-1?0:parseFloat(a[G](b+5,a[C](";",b)))},Eb=/\+/g,zc=function(a,b){b=b[ma]();if(b[G](0,3)!="ca-")b="ca-"+b;return b},X=function(a,b,c){c!=g&&W(a,b,L(c[p]()))},W=function(a,b,c){if(c!=g)a.b+=a.b[ga](a.b[t]-1)!="?"?"&"+b+"="+c:b+"="+c},Ac=function(a,b){for(var c=Vb(R(),a.u),d=[],f=[],l=[],r=c[t],s=0;s<r;s++){var y=c[s];l[o](y.s);if(!(b!=g&&b!=y.s)){d[o](y.s);f[o](zc(a,y.I))}}X(a,"client",f[0]);if(a.k)l[t]>
0&&X(a,"page_slots",l[I]());else{X(a,"slotname",d[I]());R().c[t]>0&&X(a,"page_slots",R().c[I]())}},Bc=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[C]("google_preview=",a);c=b[C]("&",a);if(c==-1){c=b[t]-1;a-=1}return b[G](0,a)+b[G](c+1,b[t])}return b},Cc=function(a,b,c){if(bb(b,c))return c.URL;return c[ja]},Ec=function(a,b,c){if(Dc(a,b,c)!=c.URL)return c[ha];return""},Dc=function(a,b,c){var d=ic(R()).getAttribute("google_page_url");if(d)return d;return Cc(a,b,c)},Fc=function(a,b,c,d){X(a,"url",
Bc(a,Dc(a,k,m),k.GA_googleEnv[F]("google_preview")));X(a,"ref",m[ja]);X(a,"lmt",(Date.parse(m.lastModified)/1000)[p]());W(a,"dt",b[H]());if(m.body){b=m.body.scrollHeight;var f=m.body.clientHeight;f&&b&&X(a,"cc",n[ea](f*100/b)[p]())}b=k.GA_googleEnv[F]("deb");b!=g&&X(a,"deb",b);b=k.GA_googleEnv[F]("haonly");b!=g&&X(a,"haonly",b);b=ic(R());i[A][C]("MSIE ")>0&&Mb(b,"google_encoding",m.charset,h);f="";if(d)f=Pb(R().a,b,R().A,a.ja);else{c=lc(R(),c);if(c==g)c=b;else Nb(c,b);f=c.g()}if(f)a.b+="&"+f},Gc=
function(a,b,c){var d=R().r,f=[];for(var l in d)Q(d[l])||f[o](L(l)+"="+L(d[l]));X(a,"cust_params",f[I]("&"));if(b._GA_googleCookieHelper){X(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.L&&X(a,"cookie_enabled","1")}b.google_new_gam_domain_checked==1&&b.google_new_gam_domain_enabled!=1&&W(a,"dblk",1);(b=Ec(a,b,c))&&X(a,"cdm",b)},Hc=function(a){Ma();var b=k;W(a,"ga_vid",b.gaGlobal.vid);W(a,"ga_sid",b.gaGlobal.sid);W(a,"ga_hid",b.gaGlobal.hid);W(a,"ga_fc",b.gaGlobal.from_cookie);X(a,
"ga_wpids",b.google_analytics_uacct)},Ic=function(a,b){for(var c in b)W(a,c,b[c])};V[u].g=function(a){this.j();var b=new Date;Ac(this,a);Gc(this,k,m);k.GA_googleEnv[F]("google_preview")!=g&&W(this,"gct",k.GA_googleEnv[F]("google_preview"));Hc(this);Fc(this,b,a,this.k);a={};Ha(a);Ic(this,a);W(this,"flash",Fa());this.b=this.b[G](0,2000);return this.b=this.b[w](/%\w?$/,"")};
var sb=function(a){return a.u},Jc=function(a,b){a=b.getAttribute("id");return a=a.substr(18,a[t]-18)},Kc=function(a,b,c,d,f,l,r){var s="google_ads_iframe_"+b,y=[];if(r){b="google_ads_div_"+b;y[o]("<div id=",b,">")}y[o]("<iframe id=",s," name=",s,' width="',f,'" height="',l,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.l?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',Hb(c),'"');d!=g&&y[o](' onload="',d,'"');y[o]("></iframe>");r&&
y[o]("</div>");a=y[I]("");m[D](a)};V[u].createDOMIframe=function(a,b){var c=ub(this,b),d=c._width_,f=c._height_;c=c._html_;var l=m.createElement("iframe");l.id="google_ads_iframe_"+b;l.name="google_ads_iframe_"+b;l.width=d;l.height=f;l.vspace=0;l.hspace=0;l.allowTransparency="true";l.scrolling="no";l.marginWidth=0;l.marginHeight=0;l.frameBorder=0;l.style.border=0;a=m.getElementById(a);a.appendChild(l);if(this.l){l[la][x][D](Hb(c));l.scrolling="auto"}else l[la][x][D](c);l[la][x].close();T(R(),b)};
function Lc(a,b){S().createDOMIframe(a,b)}J("GA_googleCreateDomIframe",Lc);
var Mc=function(){var a=[],b=m.getElementsByTagName("base");if(b)for(var c=0,d=b[t];c<d;++c){var f=b[c],l=f.getAttribute("target");if(l){a[o]({baseElement:f,originalTagValue:l});f.removeAttribute("target")}}return a},Nc=function(a){if(a)for(var b=0,c=a[t];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Oc=function(a){var b="http://"+ya+"/pagead/inject_object_div.js";if(j(yc(),10)>6)return h;if(a[C](b)<0)return h;return e},Pc=function(a,b,c){if(a.l)c=Hb(c);a=Mc();k.frames[b.name].contents=
c;b.src=Oc(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Nc(a)},Qc=function(a,b,c){var d=Jc(a,b);b=b[la]?b[la][x]:b.contentDocument;if(b==g)if(m.implementation&&m.implementation.createDocument)b=m.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")b=new ActiveXObject("Msxml.DOMDocument");else return;b.open("text/html","replace");a.l?b[D](Hb(c)):b[D](c);b.close()},Rc=function(a,b){var c=Jc(a,b),d=dc(R(),c);if(!d.O){d.O=
e;d=ub(a,c);var f=b.parentNode;if(d==g||d._html_==g){f.removeChild(b);T(R(),c)}else if(d._expandable_){f.innerHTML=d._html_;T(R(),c)}else{d._is_3pas_?Pc(a,b,d._html_):Qc(a,b,d._html_);T(R(),c)}}},Sc=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";a=ub(a,b);if(!(a==g)){c+=a._html_;c+="\n</div>\n";m[D](c);T(R(),b)}},Tc=function(a,b){a="google_ads_div_"+b;b="<div id="+a+">";b+="\n</div>\n";m[D](b);return a},Uc=function(a){if(!a.u)return e;if(Wb(R(),a.u)>0)return e;else if(Yb(R())==0)return h};
V[u].setAdContentsBySlot=function(a){hb(O,"ga_srt",R().c[t],"_ga_start");if(this.f==g){this.f=a;for(var b in a)Q(a[b])||ac(R(),b)}else for(b in a)if(!Q(a[b])){this.f[b]=a[b];ac(R(),b)}var c=h;for(b in a)if(!Q(a[b])){var d=a[b];if(c){d._cookies_=[Ya(k._GA_googleCookieHelper)];c=h}d!=g&&d._cookies_!=g&&k._GA_googleCookieHelper.setCookieInfo(d)}};function Vc(a){S().setAdContentsBySlot(a)}J("GA_googleSetAdContentsBySlot",Vc);
function Y(a){V[E](this,a);this.u=h;this.m=(new Date)[H]();this.h=a?"sync_sra":"sync"}qa(Y,V);Y[u].j=function(){this.b=this.p;X(this,"correlator",this.m[p]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlotForSync");this.k?W(this,"impl","ss"):W(this,"impl","s");var a=0,b=e;for(var c in this.f)if(!Q(this.f[c])){var d=this.f[c];if(d._is_afc_==aa){b=h;break}else a=2*a+(d._is_afc_?1:0)}b&&W(this,"prev_afc",a);this.k||Wc(this,R().c,this.f)};
var Wc=function(a,b,c){if(b&&c){for(var d=[],f=[],l=b[t]-1,r=0;r<l;r++){var s=b[r];if((s=c[s])&&s._cids_&&s._a2ids_){d[o](s._cids_[0]);f[o](s._a2ids_[0])}else{d[o]("");f[o]("")}}if(d[t]>0){b=d[I](",");f=f[I](",");X(a,"a2ids",f);X(a,"cids",b)}}},Xc=function(a,b){var c=R().a;c=c[b];if(!(c==g))if(!a.t){a.g(c.s);$b(R(),b);m[D]("<script src = '"+a.b+"'><\/script>")}};
Y[u].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.k)if(R().c[t]==1){a=R().c[0];Yc(this,a);return}for(var b in a)Q(a[b])||Yc(this,b)};function Zc(a){S().setAdContentsBySlotForSync(a)}J("GA_googleSetAdContentsBySlotForSync",Zc);Y[u].i=function(){Uc(this)};var $c=function(a){a.g(g);m[D]("<script src = '"+a.b+"'><\/script>");Zb(R())};Y[u].n=function(a){R().c[o](a);hb(O,"_ga_start",R().c[t]);if(this.k)R().c[t]==1?$c(this):Yc(this,a);else Xc(this,a)};
var ad=function(a,b,c){if(b.google_js_backfill){a="script";c[D]("<"+a+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+a+">")}},Yc=function(a,b){bd(a,k,m,b)},bd=function(a,b,c,d){var f=dc(R(),d);if(!(f==g)){f=ub(a,d);bc(R(),d);if(f==g||f._empty_){ad(a,b,c,d);T(R(),d)}else if(a.H&&!a.l)T(R(),d);else if(f._snippet_&&!f._is_afc_&&!a.l)Sc(a,d);else if(i[A][C]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";Kc(a,d,"about:blank",c,f._width_,f._height_,e)}else{a=Tc(a,d);c[D]("<script>GA_googleCreateDomIframe('"+
a+"' ,'"+d+"');<\/script>")}}};Y[u].syncAdSlotLoaded=function(a){var b=Jc(this,a);dc(R(),b);Rc(this,a)};function cd(a){S().syncAdSlotLoaded(a)}J("GA_googleSyncAdSlotLoaded",cd);function Z(a){V[E](this,a);this.m=(new Date)[H]();this.h="async"}qa(Z,V);Z[u].j=function(){this.b=this.p;dd(this);X(this,"correlator",this.m[p]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlot");W(this,"impl","a")};
var dd=function(a){a.delay=500;var b=k.GA_googleEnv[F]("google_async_delay");if(b!=g)a.delay=1000*b};Z[u].i=function(){if(Uc(this))this.t||k.setTimeout("GA_googleReallyFetchAds();",this.INITIAL_ASYNC_DELAY)};
Z[u].reallyFetchAds=function(){if(!(Wb(R(),this.u)==0)){var a=m.getElementsByTagName("head")[0];if(this.k){var b=m.createElement("script");b.src=this.g(g);a.appendChild(b);Zb(R())}else{var c=R().a;for(var d in c)if(!Q(c[d])){b=m.createElement("script");b.src=this.g(d);a.appendChild(b);$b(R(),d)}}}};function ed(){S().reallyFetchAds()}J("GA_googleReallyFetchAds",ed);
Z[u].n=function(a){var b=dc(R(),a);if(!(b==g)){R().c[o](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=tb(R(),a);Kc(this,a,"about:blank",b,c._width_,c._height_,e)}};Z[u].asyncAdSlotLoaded=function(a){var b=Jc(this,a);dc(R(),b);!this.t&&!this.H&&fd(this,a)};function gd(a){S().asyncAdSlotLoaded(a)}J("GA_googleAsyncAdSlotLoaded",gd);var fd=function(a,b){var c=Jc(a,b),d=dc(R(),c);if(a.f==g||a.f[c]==g){if(!(d.Q>30)){k.setTimeout(function(){fd(S(),b)},a.delay);d.Q++}}else Rc(a,b)};Z[u].F=function(){};
function $(a){V[E](this,a);this.m=(new Date)[H]();this.h="fallback"}qa($,V);$[u].j=function(){this.b=this.p;X(this,"correlator",this.m[p]());W(this,"output","html");W(this,"impl","fb")};$[u].i=function(){Uc(this)};$[u].w=function(a){if(this.k){this.g(g);a=this.b+"&currentslot="+L(a)}else a=this.g(a);return a};$[u].n=function(a){var b=tb(R(),a);if(!(b==g)){R().c[o](a);if(!this.t){var c=this.w(a);Kc(this,a,c,g,b._width_,b._height_,e)}}};
function hd(a){V[E](this,a);this.m=(new Date)[H]();this.J=e;this.h="iframe"}qa(hd,V);hd[u].j=function(){this.b=this.p;X(this,"correlator",this.m[p]());W(this,"output","html");W(this,"impl","ifr")};hd[u].i=function(){Uc(this)};hd[u].w=function(a){if(this.k){this.g(g);a=this.b+"&currentslot="+L(a)}else a=this.g(a);return a};hd[u].n=function(a){var b=tb(R(),a);if(!(b==g)){R().c[o](a);if(!this.t){var c=this.w(a);Kc(this,a,c,g,b._width_,b._height_,e)}}};
var id=function(){if(Ea()){var a=yc();return a<=5}else if(Ca("firefox")){var b=i[A][C]("Firefox")+8;a=j(i[A][ga](b),10);b=i[A][v](b);return a<1}else if(Ca("safari")){b=i[A][C]("Safari")+7;b=i[A][v](b);a=j(b,10);return a<412}else if(k.opera!=g){b=i[A][C]("Opera")+6;b=i[A][v](b);a=j(b,10);return a<9}else if(!Ea()&&!Ca("safari")&&Ca("mozilla")){b=i[A][C]("Netscape")+9;b=i[A][v](b);a=j(b,10);return a<7}else return e},jd=function(){if(Ea()){var a=yc();return a>5}else if(Ca("firefox")){a=i[A][C]("Firefox")+
8;var b=j(i[A][ga](a),10);i[A][v](a);return b>1}return h},kd=function(){if(id())return"fallback";else if(k.google_delayFetch&&jd())return"async";return"sync"},lb=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=k.GA_googleEnv[F]("google_ad_impl");if(b==g)b=kd()}switch(b){case "async":return new Z(h);case "sync":return new Y(h);case "sync_sra":return new Y(e);case "fallback":return new $(h);case "iframe":return new hd(h);default:return new $(h)}},ld;
function R(){ld||(ld=new Ab(Ia));return ld}function zb(a){delete ld;ld=a}var md;function S(){md||(md=g);return md}function kb(a){delete md;md=a}if(typeof k.GA_googleEnv=="undefined")k.GA_googleEnv=new Fb;if(typeof k.GA_googleAdCapture=="undefined")k.GA_googleAdCapture=new Ib;if(k._GA_googleCookieHelper==g)k._GA_googleCookieHelper=new Ta;O.tick("js_parse","js_load");O.tick("jl");
})()
